[[log]]
# Possible modes are trustix-log, trustix-follower & trustix-gossip
# Note that right now trustix-gossip is a TODO
mode = "trustix-log"

[log.storage]
type = "git"

[log.storage.git]
# Do note that "remote" is set at EVERY startup to follow declarative config
remote = "git@github.com:someuser/trustix-log.git"
path = "./repo"
# Only used by trustix-log mode
commiter = "trustix"
email = "trustix@example.com"

[log.signer]
# The difference between type & key-type is that type is the Trustix "signer mode" while key-type is the type of key
# Another signer (lets say PKCS11) could be implemented that uses the same key-type but a different signing backend
type = "ed25519"
key-type = "ed25519"
public-key = "2uy8gNIOYEewTiV7iB7cUxBGpXxQtdlFepFoRvJTCJo="  # Base64 encoded public key

# Implementation dependent
[log.signer.ed25519]
private-key-path = "./priv"  # Path to base64 encode private key file (should not be in the nix store)
