[storage]
type = "native"

[storage.native]

[decider]

[[decider."nix"]]
engine = "percentage"

[decider."nix".percentage]
minimum = 50

[signers.snakeoil]
type = "ed25519"

# Implementation dependent
[signers.snakeoil.ed25519]
private-key-path = "./dev/priv"  # Path to base64 encode private key file (should not be in the nix store)

[[publishers]]
signer = "snakeoil"
protocol = "nix"

[publishers.meta]
upstream = "https://cache.nixos.org"

[publishers.publicKey]
type = "ed25519"
key = "2uy8gNIOYEewTiV7iB7cUxBGpXxQtdlFepFoRvJTCJo="  # Base64 encoded public key
