[storage]
type = "native"

[storage.native]

[[decider]]
engine = "percentage"

[decider.percentage]
minimum = 50

[[publisher]]

[publisher.meta]
upstream = "https://cache.nixos.org"

[publisher.key]
type = "ed25519"
pub = "2uy8gNIOYEewTiV7iB7cUxBGpXxQtdlFepFoRvJTCJo="  # Base64 encoded public key

[publisher.signer]
type = "ed25519"

# Implementation dependent
[publisher.signer.ed25519]
private-key-path = "./dev/priv"  # Path to base64 encode private key file (should not be in the nix store)
