[storage]
type = "native"

[storage.native]

[decider]

[[decider."nix"]]
engine = "percentage"

[decider."nix".percentage]
minimum = 50

[signer.snakeoil]
type = "ed25519"

# Implementation dependent
[signer.snakeoil.ed25519]
private-key-path = "./dev/priv"  # Path to base64 encode private key file (should not be in the nix store)

[[publisher]]
signer = "snakeoil"
protocol = "nix"

[publisher.meta]
upstream = "https://cache.nixos.org"

[publisher.key]
type = "ed25519"
pub = "2uy8gNIOYEewTiV7iB7cUxBGpXxQtdlFepFoRvJTCJo="  # Base64 encoded public key
