[storage]
type = "native"

[storage.native]

[[decider]]
engine = "percentage"

[decider.percentage]
minimum = 50

[[publisher]]

[publisher.meta]
upstream = "https://cache.nixos.org"

[publisher.signer]
# The difference between type & key-type is that type is the Trustix "signer mode" while key-type is the type of key
# Another signer (lets say PKCS11) could be implemented that uses the same key-type but a different signing backend
type = "ed25519"
key-type = "ed25519"
public-key = "2uy8gNIOYEewTiV7iB7cUxBGpXxQtdlFepFoRvJTCJo="  # Base64 encoded public key

# Implementation dependent
[publisher.signer.ed25519]
private-key-path = "./priv"  # Path to base64 encode private key file (should not be in the nix store)
