name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v12
    - uses: actions/checkout@v1
    - name: build
      run: make build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v12
    - uses: actions/checkout@v1
    - name: test
      run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v12
    - uses: actions/checkout@v1
    - name: lint
      run: make lint

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v12
    - uses: actions/checkout@v1
    - name: format
      run: make format
